### ISSUE TITLE
Explicit reference to Buffer class (node)

### ISSUE THREAD

**Issue by GaelBi** [rsocket/rsocket-js#267]
Hello,

Working with Angular 16, I met the following error : 
```
ReferenceError: Buffer is not defined
    at serializeSetupFrame (Codecs.js:315:11)
    at serializeFrame (Codecs.js:227:20)
    at WebsocketDuplexConnection.send (WebsocketDuplexConnection.js:86:55)
    at ClientServerInputMultiplexerDemultiplexer.send (ClientServerMultiplexerDemultiplexer.js:144:23)
    at RSocketConnector.<anonymous> (RSocketConnector.js:146:80)
```

I had to expose in the global scope manually the reference to the Buffer class. But, like it is mentioned in the suggestion from the official documentation, maybe, it would be preferable to set an explicit reference of this class when it is used ?

The official documentation : https://nodejs.org/api/buffer.html#buffer
_"While the Buffer class is available within the global scope, it is still recommended to explicitly reference it via an import or require statement."_

## Desired solution
Explicit import of Buffer when it is required (like in Codecs.ts).
`import { Buffer } from 'node:buffer';`

**Comment by GaelBi** [comment]
Hi @viglucci , 

Thanks for your answer.
I am using the 1.0.0-alpha.3 version.
No, I think the issue should be resolved with this import. Indeed, the buffer module seems to be now compatible with Browser environment, my solution has been to import and expose it in window context (without any polyfill).

The polyfills seem to be less and less used, for exemple, we can read in the documentation of webpack 5 : "...the module landscape changed and many module uses are now written mainly for frontend purposes..."
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

Regards,
Gaël

**Comment by viglucci** [comment]
Hey @GaelBi, thanks for the additional comment.

I'm happy to give this a try and see if importing from 'node:buffer' produces a bundle which is both browser compatible and doesn't require an explicit Pollyfill.

Alternatively, if you'd be interested in submitting a branch doing so I would be more than happy to review the results there as well.

**Comment by sdack-cloud** [comment]
> npm install buffer

import { createApp } from 'vue';
import App from './App.vue';
import { Buffer } from 'buffer';

// 将 Buffer 挂载到全局对象（如 window）
window.Buffer = Buffer;


const app = createApp(App);

app.mount('#app');
