### ISSUE TITLE
RSocketJS throws exception with >7.8KB payload size

### ISSUE THREAD

**Issue by sameerasaad** [rsocket/rsocket-js#98]
RSocket-JS client was able to send payload size of 15KB to the RSocket Java server after the Java server finished processing and sent the payload back to the RSocket-JS RSocketClient (RequestResponse interaction )throws an exception
![image](https://user-images.githubusercontent.com/16827292/92079679-2bcc7e80-ed75-11ea-84ac-7f91047fceef.png)

the code is failing in the foreach when going through the the frames 
![image](https://user-images.githubusercontent.com/16827292/92079827-6e8e5680-ed75-11ea-813f-2ae2e998d9a4.png)
  

## Expected Behavior

RSocketJS - RSocketClient is able to receive data with any payload size using the RequestResponse interaction 
## Actual Behavior

getting the following error when the payload size is greater than 7.8KB
![image](https://user-images.githubusercontent.com/16827292/92080260-186de300-ed76-11ea-8ab9-1288e77e9c8b.png)

## Steps to Reproduce

```

//server setup 

his.client = new RSocketClient({
            setup: {
                keepAlive: 800,
                lifetime: 1800,
                dataMimeType: 'application/json',
                metadataMimeType: 'application/json',
                //errorHandler: new Error(),
            },
            responder: new Responder(),
            transport: new RSocketWebSocketClient({
                url: url,
                debug: true,
            }),
        });
// method to publish to RSocket java server 
sendMessage(){

        this.s
            .requestResponse({
                data:'{"body":"Repulsive questions contented him few extensive supported. Of remarkably thoroughly he appearance in. Supposing tolerably applauded or of be. Suffering unfeeling so objection agreeable allowance me of. Ask within entire season sex common far who family. As be valley warmth assure on. Park girl they rich hour new well way you. Face ye be me been room we sons fond. Greatly cottage thought fortune no mention he. Of mr certainty arranging am smallness by conveying. Him plate you allow built grave. Sigh sang nay sex high yet door game. She dissimilar was favourable unreserved nay expression contrasted saw. Past her find she like bore pain open. Shy lose need eyes son not shot. Jennings removing are his eat dashwood. Middleton as pretended listening he smallness perceived. Now his but two green spoil drift. Society excited by cottage private an it esteems. Fully begin on by wound an. Girl rich in do up or both. At declared in as rejoiced of together. He impression collecting delightful unpleasant by prosperous as on. End too talent she object mrs wanted remove giving. New had happen unable uneasy. Drawings can followed improved out sociable not. Earnestly so do instantly pretended. See general few civilly amiable pleased account carried. Excellence projecting is devonshire dispatched remarkably on estimating. Side in so life past. Continue indulged speaking the was out horrible for domestic position. Seeing rather her you not esteem men settle genius excuse. Deal say over you age from. Comparison new ham melancholy son themselves. Do commanded an shameless we disposing do. Indulgence ten remarkably nor are impression out. Power is lived means oh every in we quiet. Remainder provision an in intention. Saw supported too joy promotion engrossed propriety. Me till like it sure no sons. Eat imagine you chiefly few end ferrars compass. Be visitor females am ferrars inquiry. Latter law remark two lively thrown. Spot set they know rest its. Raptures law diverted believed jennings consider children the see. Had invited beloved carried the colonel. Occasional principles discretion it as he unpleasing boisterous. She bed sing dear now son half. Acceptance middletons me if discretion boisterous travelling an. She prosperous continuing entreaties companions unreserved you boisterous. Middleton sportsmen sir now cordially ask additions for. You ten occasional saw everything but conviction. Daughter returned quitting few are day advanced branched. Do enjoyment defective objection or we if favourite. At wonder afford so danger cannot former seeing. Power visit charm money add heard new other put. Attended no indulged marriage is to judgment offering landlord. Seen you eyes son show. Far two unaffected one alteration apartments celebrated but middletons interested. Described deficient applauded consisted my me do. Passed edward two talent effect seemed engage six. On ye great do child sorry lived. Proceed cottage far letters ashamed get clothes day. Stairs regret at if matter to. On as needed almost at basket remain. By improved sensible servants children striking in surprise. She who arrival end how fertile enabled. Brother she add yet see minuter natural smiling article painted. Themselves at dispatched interested insensible am be prosperous reasonably it. In either so spring wished. Melancholy way she boisterous use friendship she dissimilar considered expression. Sex quick arose mrs lived. Mr things do plenty others an vanity myself waited to. Always parish tastes at as mr father dining at. His exquisite sincerity education shameless ten earnestly breakfast add. So we me unknown as improve hastily sitting forming. Especially favourable compliment but thoroughly unreserved saw she themselves. Sufficient impossible him may ten insensible put continuing. Oppose exeter income simple few joy cousin but twenty. Scale began quiet up short wrong in in. Sportsmen shy forfeited engrossed may can. Repulsive questions contented him few extensive supported. Of remarkably thoroughly he appearance in. Supposing tolerably applauded or of be. Suffering unfeeling so objection agreeable allowance me of. Ask within entire season sex common far who family. As be valley warmth assure on. Park girl they rich hour new well way you. Face ye be me been room we sons fond. Greatly cottage thought fortune no mention he. Of mr certainty arranging am smallness by conveying. Him plate you allow built grave. Sigh sang nay sex high yet door game. She dissimilar was favourable unreserved nay expression contrasted saw. Past her find she like bore pain open. Shy lose need eyes son not shot. Jennings removing are his eat dashwood. Middleton as pretended listening he smallness perceived. Now his but two green spoil drift. Society excited by cottage private an it esteems. Fully begin on by wound an. Girl rich in do up or both. At declared in as rejoiced of together. He impression collecting delightful unpleasant by prosperous as on. End too talent she object mrs wanted remove giving. New had happen unable uneasy. Drawings can followed improved out sociable not. Earnestly so do instantly pretended. See general few civilly amiable pleased account carried. Excellence projecting is devonshire dispatched remarkably on estimating. Side in so life past. Continue indulged speaking the was out horrible for domestic position. Seeing rather her you not esteem men settle genius excuse. Deal say over you age from. Comparison new ham melancholy son themselves. Do commanded an shameless we disposing do. Indulgence ten remarkably nor are impression out. Power is lived means oh every in we quiet. Remainder provision an in intention. Saw supported too joy promotion engrossed propriety. Me till like it sure no sons. Eat imagine you chiefly few end ferrars compass. Be visitor females am ferrars inquiry. Latter law remark two lively thrown. Spot set they know rest its. Raptures law diverted believed jennings consider children the see. Had invited beloved carried the colonel. Occasional principles discretion it as he unpleasing boisterous. She bed sing dear now son half. Acceptance middletons me if discretion boisterous travelling an. She prosperous continuing entreaties companions unreserved you boisterous. Middleton sportsmen sir now cordially ask additions for. You ten occasional saw everything but conviction. Daughter returned quitting few are day advanced branched. Do enjoyment defective objection or we if favourite. At wonder afford so danger cannot former seeing. Power visit charm money add heard new other put. Attended no indulged marriage is to judgment offering landlord. Seen you eyes son show. Far two unaffected one alteration apartments celebrated but middletons interested. Described deficient applauded consisted my me do. Passed edward two talent effect seemed engage six. On ye great do child sorry lived. Proceed cottage far letters ashamed get clothes day. Stairs regret at if matter to. On as needed almost at basket remain. By improved sensible servants children striking in surprise. She who arrival end how fertile enabled. Brother she add yet see minuter natural smiling article painted. Themselves at dispatched interested insensible am be prosperous reasonably it. In either so spring wished. Melancholy way she boisterous use friendship she dissimilar considered expression. Sex quick arose mrs lived. Mr things do plenty others an vanity myself waited to. Always parish tastes at as mr father dining at. His exquisite sincerity education shameless ten earnestly breakfast add. So we me unknown as improve hastily sitting forming. Especially favourable compliment but thoroughly unreserved saw she themselves. Sufficient impossible him may ten insensible put continuing. Oppose exeter income simple few joy cousin but twenty. Scale began quiet up short wrong in in. Sportsmen shy forfeited engrossed may can. Repulsive questions contented him few extensive supported. Of remarkably thoroughly he appearance in. Supposing tolerably applauded or of be. Suffering unfeeling so objection agreeable allowance me of. Ask within entire season sex common far who family. As be valley warmth assure on. Park girl they rich hour new well way you. Face ye be me been room we sons fond. Greatly cottage thought fortune no mention he. Of mr certainty arranging am smallness by conveying. Him plate you allow built grave. Sigh sang nay sex high yet door game. She dissimilar was favourable unreserved nay expression contrasted saw. Past her find she like bore pain open. Shy lose need eyes son not shot. Jennings removing are his eat dashwood. Middleton as pretended listening he smallness perceived. Now his but two green spoil drift. Society excited by cottage private an it esteems. Fully begin on by wound an. Girl rich in do up or both. At declared in as rejoiced of together. He impression collecting delightful unpleasant by prosperous as on. End too talent she object mrs wanted remove giving. New had happen unable uneasy. Drawings can followed improved out sociable not. Earnestly so do instantly pretended. See general few civilly amiable pleased account carried. Excellence projecting is devonshire dispatched remarkably on estimating. Side in so life past. Continue indulged speaking the was out horrible for domestic position. Seeing rather her you not esteem men settle genius excuse. Deal say over you age from. Comparison new ham melancholy son themselves. Do commanded an shameless we disposing do. Indulgence ten remarkably nor are impression out. Power is lived means oh every in we quiet. Remainder provision an in intention. Saw supported too joy promotion engrossed propriety. Me till like it sure no sons. Eat imagine you chiefly few end ferrars compass. Be visitor females am ferrars inquiry. Latter law remark two lively thrown. Spot set they know rest its. Raptures law diverted believed jennings consider children the see. Had invited beloved carried the colonel. Occasional principles discretion it as he unpleasing boisterous. She bed sing dear now son half. Acceptance middletons me if discretion boisterous travelling an. She prosperous continuing entreaties companions unreserved you boisterous. Middleton sportsmen sir now cordially ask additions for. You ten occasional saw everything but conviction. Daughter returned quitting few are day advanced branched. Do enjoyment defective objection or we if favourite. At wonder afford so danger cannot former seeing. Power visit charm money add heard new other put. Attended no indulged marriage is to judgment offering landlord. Seen you eyes son show. Far two unaffected one alteration apartments celebrated but middletons interested. Described deficient applauded consisted my me do. Passed edward two talent effect seemed engage six. On ye great do child sorry lived. Proceed cottage far letters ashamed get clothes day. Stairs regret at if matter to. On as needed almost at basket remain. By improved sensible servants children striking in surprise. She who arrival end how fertile enabled. Brother she add yet see minuter natural smiling article painted. Themselves at dispatched interested insensible am be prosperous reasonably it. In either so spring wished. Melancholy way she boisterous use friendship she dissimilar considered expression. Sex quick arose mrs lived. Mr things do plenty others an vanity myself waited to. Always parish tastes at as mr father dining at. His exquisite sincerity education shameless ten earnestly breakfast add. So we me unknown as improve hastily sitting forming. Especially favourable compliment but thoroughly unreserved saw she themselves. Sufficient impossible him may ten insensible put continuing. Oppose exeter income simple few joy cousin but twenty. Scale began quiet up short wrong in in. Sportsmen shy forfeited engrossed may can."}',
                metadata: '{"operation":"publishEvent"}',
            })
            .subscribe({
                onComplete: response => {
                    const data = response.data;
                    if (data) {
                        console.log(`Requester response:`,data);

                    }
                },
                onError: error => console.log(`Requester error: ${error.message}`),
            });
}
```

```
//code receiving data from RSocket server 
class Responder {
    requestResponse(payload) {
        let res = JSON.parse(payload.data);
        console.log('Data received from RSocket server',res);
        return Single.of({
                data: `{"clientReceived":"true"}`,
            }
        );
    }
}

```

## Your Environment

* RSocket version(s) used:^0.0.19
* Other relevant libraries versions (eg. `netty`, ...):
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)):
* OS and version (eg `uname -a`):

**Comment by OlegDokuka** [comment]
@sameerasaad do you have fragmentation enabled on the server-side? If so, then this is the reason for the mentioned issue. 

As of now, RSocket-Js does not support reassembly of fragmented frames.

Cheers,
Oleh

**Comment by sameerasaad** [comment]
@OlegDokuka  No, the fragmentation is not enabled in the server, Do you have test where you send and receive big payloads using request-response in RSocket-js?

Thanks,
Sameer

**Comment by sameerasaad** [comment]
By the way the same large payload i was able to receive it using Java client with no issues but i got the above error when I receive the same large payload in RSocket-js

Thanks,
Sameer

**Comment by akulkarni-01** [comment]
@OlegDokuka , I see the same issue with latest version of Rsocket JS - 0.0.22

**Comment by OlegDokuka** [comment]
@akulkarni-01 can you please provide me with a working example that reproduces this issue, since I'm struggling to reproduce that locally using the following app (https://github.com/OlegDokuka/rsocket-crosslanguage-example/tree/fragmentation)

**Comment by akulkarni-01** [comment]
@OlegDokuka 
Sure I can do that. 
Just to clarify, fragmentation is not enabled on the server. I am sending and receiving large payloads using request-response using RSocket-js

**Comment by OlegDokuka** [comment]
@akulkarni-01 sounds like an unrelated problem. Let me try to do something similar

Also, it can be related to the browser setup itselves

**Comment by OlegDokuka** [comment]
@akulkarni-01 I tried to follow the mentioned setup (no fragmentation enabled on the server side + message size above 7 kb) and I still have no issues :(

![image](https://user-images.githubusercontent.com/5380167/103692792-fb098980-4fa0-11eb-9c3c-d612f1ff7635.png)

**Comment by akulkarni-01** [comment]
@OlegDokuka thanks for checking .I am testing in RSocket-Java-server 1.0.0-RC6
I will try out my scenario with the same Chrome version  and RSocket-Java-server 1.1.0

**Comment by myklt** [comment]
> using the following app (https://github.com/OlegDokuka/rsocket-crosslanguage-example/tree/fragmentation)

@OlegDokuka , I've just played with your example. It works as expected as long as the size of the message is not too big. I increased the message size **sent from UI** to 150kb and then the following message was thrown in Java:

```
2021-01-18 17:22:17.685 ERROR 300 --- [ctor-http-nio-2] io.rsocket.core.RSocketRequester         : Unexpected error during frame handling

java.lang.IllegalArgumentException: Frame type 27 is unknown
        at io.rsocket.frame.FrameType.fromEncodedType(FrameType.java:241) ~[rsocket-core-1.1.0.jar:na]
        at io.rsocket.frame.FrameHeaderCodec.frameType(FrameHeaderCodec.java:104) ~[rsocket-core-1.1.0.jar:na]
        at io.rsocket.core.RSocketRequester.handleIncomingFrames(RSocketRequester.java:201) ~[rsocket-core-1.1.0.jar:na]
``` 

I tried to find out what is the maximum size it can still process and it was `130885` chars. Is this expected or there is something missing in this example setup?

**Comment by akulkarni-01** [comment]
> @OlegDokuka thanks for checking .I am testing in RSocket-Java-server 1.0.0-RC6
> I will try out my scenario with the same Chrome version and RSocket-Java-server 1.1.0

@OlegDokuka - My test scenario worked with newer version of Rsocket-java-server . I tested upto 65 kb

**Comment by OlegDokuka** [comment]
@myklt It is not related to the mentioned case. What you experience is Chrome browser fragmentation over the websocket (for more info see https://bugs.chromium.org/p/chromium/issues/detail?id=517090). 

In order to handle such fragmented frames in rsocket-java, you have to enable [aggregation](https://github.com/reactor/reactor-netty/blob/master/reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketInbound.java#L68) of the incoming frames. In RSocket Java you may do that as in the following [example](https://github.com/rsocket/rsocket-java/blob/master/rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketAggregationSample.java)

**Comment by OlegDokuka** [comment]
@akulkarni-01 thanks for checking!

**Comment by myklt** [comment]
@OlegDokuka thanks a lot for those deep insights! It is really helpful. Interesting that with Node.js WebSocket server there is no issue at all.

**Comment by OlegDokuka** [comment]
@myklt in rsocket-js this is done on the transport level, but since in rsocket Java, and of course performance wise, you have more control - you may decide to aggregate or not (assume aggregation will produce more garbage, hence having no aggregation provides less performance impact)
